// Question Bank with randomizable options - 15 questions per category
const questionBank = [
  // HTML Questions (15)
  {
    id: 1,
    category: "HTML",
    question: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "High Tech Modern Language",
      "Home Tool Markup Language",
      "Hyperlink and Text Markup Language",
    ],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 2,
    category: "HTML",
    question: "Which HTML element is used for the largest heading?",
    options: ["<h6>", "<h1>", "<heading>", "<header>"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 3,
    category: "HTML",
    question: "What is the correct HTML element for inserting a line break?",
    options: ["<break>", "<br>", "<lb>", "<newline>"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 4,
    category: "HTML",
    question: "Which attribute is used to specify the URL of a link?",
    options: ["src", "href", "link", "url"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 5,
    category: "HTML",
    question: "What does the <meta> tag define?",
    options: ["Metadata about the HTML document", "Main content", "Menu items", "Media files"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 6,
    category: "HTML",
    question: "Which HTML element is used to define important text?",
    options: ["<important>", "<b>", "<strong>", "<i>"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 7,
    category: "HTML",
    question: "What is the correct HTML for creating a hyperlink?",
    options: [
      "<a url='http://www.example.com'>Example</a>",
      "<a href='http://www.example.com'>Example</a>",
      "<a>http://www.example.com</a>",
      "<a name='http://www.example.com'>Example</a>",
    ],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 8,
    category: "HTML",
    question: "Which character is used to indicate an end tag?",
    options: ["<", "*", "/", "^"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 9,
    category: "HTML",
    question: "What is the correct HTML for making a checkbox?",
    options: ["<input type='check'>", "<input type='checkbox'>", "<checkbox>", "<check>"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 10,
    category: "HTML",
    question: "What is the correct HTML for making a text input field?",
    options: ["<input type='textfield'>", "<textinput type='text'>", "<input type='text'>", "<textfield>"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 11,
    category: "HTML",
    question: "Which HTML attribute specifies an alternate text for an image?",
    options: ["longdesc", "alt", "src", "title"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 12,
    category: "HTML",
    question: "What is the correct HTML for making a drop-down list?",
    options: ["<input type='dropdown'>", "<select>", "<input type='list'>", "<list>"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 13,
    category: "HTML",
    question: "What is the correct HTML for inserting an image?",
    options: [
      "<img href='image.gif' alt='MyImage'>",
      "<img>image.gif</img>",
      "<image src='image.gif' alt='MyImage'>",
      "<img src='image.gif' alt='MyImage'>",
    ],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 14,
    category: "HTML",
    question: "Which HTML element defines the title of a document?",
    options: ["<meta>", "<title>", "<head>", "<header>"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 15,
    category: "HTML",
    question: "What does the <tbody> element represent?",
    options: ["Table body", "Text body", "Table border", "Table background"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 16,
    category: "HTML",
    question: "Which tag is used to create an unordered list in HTML?",
    options: ["<ol>", "<ul>", "<li>", "<list>"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 17,
    category: "HTML",
    question: "What is the purpose of the 'alt' attribute in the <img> tag?",
    options: [
      "To specify the source of the image",
      "To provide alternative text for the image",
      "To define the image's alignment",
      "To set the image's border",
    ],
    correctAnswer: 1,
    difficulty: "medium",
  },

  // Movies Questions (15)
  {
    id: 18,
    category: "Movies",
    question: 'Who directed the movie "Inception"?',
    options: ["Steven Spielberg", "Christopher Nolan", "Martin Scorsese", "Quentin Tarantino"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 19,
    category: "Movies",
    question: "Which movie won the Academy Award for Best Picture in 2020?",
    options: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 20,
    category: "Movies",
    question: "In which movie did Tom Hanks play a character named Forrest?",
    options: ["Cast Away", "Philadelphia", "Forrest Gump", "Big"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 21,
    category: "Movies",
    question: 'Who played the main character in "The Matrix"?',
    options: ["Brad Pitt", "Keanu Reeves", "Will Smith", "Tom Cruise"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 22,
    category: "Movies",
    question: 'Which movie features the quote "May the Force be with you"?',
    options: ["Star Trek", "Star Wars", "Guardians of the Galaxy", "Interstellar"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 23,
    category: "Movies",
    question: 'Who directed "Pulp Fiction"?',
    options: ["Martin Scorsese", "Quentin Tarantino", "Steven Spielberg", "Francis Ford Coppola"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 24,
    category: "Movies",
    question: 'In "The Lord of the Rings", what is the name of Gandalf\'s horse?',
    options: ["Shadowfax", "Roach", "Bucephalus", "Pegasus"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 25,
    category: "Movies",
    question: 'Which actor played Jack in "Titanic"?',
    options: ["Brad Pitt", "Leonardo DiCaprio", "Matt Damon", "Johnny Depp"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 26,
    category: "Movies",
    question: "What is the highest-grossing film of all time?",
    options: ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars: The Force Awakens"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 27,
    category: "Movies",
    question: 'Who played the Joker in "The Dark Knight"?',
    options: ["Jack Nicholson", "Heath Ledger", "Joaquin Phoenix", "Jared Leto"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 28,
    category: "Movies",
    question: 'What is the name of the song in "Titanic"?',
    options: ["My Heart Will Go On", "Can't Stop the World", "Someone Like You", "Imagine"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 29,
    category: "Movies",
    question: 'In which movie does the character say "I\'ll be back"?',
    options: ["Predator", "Conan the Barbarian", "The Terminator", "Total Recall"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 30,
    category: "Movies",
    question: 'Who directed "Jaws"?',
    options: ["George Lucas", "Steven Spielberg", "Martin Scorsese", "Francis Ford Coppola"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 31,
    category: "Movies",
    question: "Which movie won the first ever Academy Award for Best Picture?",
    options: ["Wings", "Sunrise", "The Jazz Singer", "7th Heaven"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 32,
    category: "Movies",
    question: 'In "Finding Nemo", what type of fish is Nemo?',
    options: ["Angelfish", "Clownfish", "Goldfish", "Pufferfish"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 33,
    category: "Movies",
    question: "Who plays James Bond in 'Casino Royale'?",
    options: ["Pierce Brosnan", "Daniel Craig", "Sean Connery", "Roger Moore"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 34,
    category: "Movies",
    question: "What year was the first 'Harry Potter' movie released?",
    options: ["2000", "2001", "2002", "2003"],
    correctAnswer: 1,
    difficulty: "easy",
  },

  // Logic Questions (15)
  {
    id: 35,
    category: "Logic",
    question: "What comes next in the sequence: 2, 6, 12, 20, 30, ?",
    options: ["40", "42", "44", "46"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 36,
    category: "Logic",
    question: 'If A = 1, B = 2, C = 3, what does "CAB" equal?',
    options: ["6", "321", "312", "123"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 37,
    category: "Logic",
    question:
      "If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?",
    options: ["100 minutes", "20 minutes", "5 minutes", "1 minute"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 38,
    category: "Logic",
    question: "What is the next number in the sequence: 1, 1, 2, 3, 5, 8, ?",
    options: ["11", "13", "15", "16"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 39,
    category: "Logic",
    question: "If all roses are flowers and some flowers fade quickly, which statement is true?",
    options: ["All roses fade quickly", "Some roses fade quickly", "No roses fade quickly", "Cannot be determined"],
    correctAnswer: 3,
    difficulty: "hard",
  },
  {
    id: 40,
    category: "Logic",
    question: "What comes next: O, T, T, F, F, S, S, E, ?",
    options: ["N", "T", "E", "I"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 41,
    category: "Logic",
    question: "If you have a 3-gallon jug and a 5-gallon jug, how can you measure exactly 4 gallons?",
    options: [
      "Fill 5, pour into 3, empty 3, pour remaining 2 from 5 into 3, fill 5, pour into 3 until full",
      "Fill 3 twice",
      "Fill 5, drink 1 gallon",
      "Impossible",
    ],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 42,
    category: "Logic",
    question: "What comes next in the sequence: 2, 6, 12, 20, 30, 42, ?",
    options: ["54", "56", "58", "60"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 43,
    category: "Logic",
    question: "If today is Monday, what day will it be 100 days from now?",
    options: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 44,
    category: "Logic",
    question: "What comes next in the pattern: 1, 4, 9, 16, 25, ?",
    options: ["30", "35", "36", "49"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 45,
    category: "Logic",
    question: "If you rearrange the letters 'CIFAIPC', you would have the name of a:",
    options: ["City", "Animal", "Ocean", "Country"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 46,
    category: "Logic",
    question: "What is the next letter in this sequence: J, F, M, A, M, J, J, A, S, O, N, ?",
    options: ["D", "J", "M", "Y"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 47,
    category: "Logic",
    question: "If 2 + 3 = 10, 7 + 2 = 63, 6 + 5 = 66, then 8 + 4 = ?",
    options: ["96", "84", "48", "32"],
    correctAnswer: 0,
    difficulty: "hard",
  },
  {
    id: 48,
    category: "Logic",
    question: "What number should replace the question mark: 4, 7, 11, 18, 29, ?",
    options: ["47", "43", "41", "39"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 49,
    category: "Logic",
    question: "If you multiply me by any other number, the answer will always be the same. What number am I?",
    options: ["0", "1", "10", "100"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 50,
    category: "Logic",
    question: "Which word does not belong: pen, pencil, eraser, book?",
    options: ["Pen", "Pencil", "Eraser", "Book"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 51,
    category: "Logic",
    question: "What has an eye, but cannot see?",
    options: ["Needle", "Potato", "Hurricane", "Tornado"],
    correctAnswer: 0,
    difficulty: "medium",
  },

  // Science Questions (15)
  {
    id: 52,
    category: "Science",
    question: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 53,
    category: "Science",
    question: "How many bones are in the adult human body?",
    options: ["206", "208", "210", "212"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 54,
    category: "Science",
    question: "What planet is known as the Red Planet?",
    options: ["Venus", "Jupiter", "Mars", "Saturn"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 55,
    category: "Science",
    question: "Which gas makes up about 78% of Earth's atmosphere?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 56,
    category: "Science",
    question: "What is the hardest natural substance on Earth?",
    options: ["Gold", "Iron", "Diamond", "Quartz"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 57,
    category: "Science",
    question: "What is the speed of light in a vacuum?",
    options: ["300,000 km/s", "150,000 km/s", "299,792,458 m/s", "186,000 miles/s"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 58,
    category: "Science",
    question: "What is the chemical formula for water?",
    options: ["H2O", "CO2", "NaCl", "CH4"],
    correctAnswer: 0,
    difficulty: "easy",
  },
  {
    id: 59,
    category: "Science",
    question: "Which organ in the human body produces insulin?",
    options: ["Liver", "Kidney", "Pancreas", "Heart"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 60,
    category: "Science",
    question: "What is the smallest unit of matter?",
    options: ["Molecule", "Atom", "Proton", "Electron"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 61,
    category: "Science",
    question: "How many chambers does a human heart have?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 62,
    category: "Science",
    question: "What type of animal is a Komodo dragon?",
    options: ["Snake", "Lizard", "Crocodile", "Turtle"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 63,
    category: "Science",
    question: "What is the most abundant gas in the universe?",
    options: ["Oxygen", "Nitrogen", "Hydrogen", "Helium"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 64,
    category: "Science",
    question: "Which scientist developed the theory of evolution?",
    options: ["Isaac Newton", "Albert Einstein", "Charles Darwin", "Galileo Galilei"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 65,
    category: "Science",
    question: "What is the pH of pure water?",
    options: ["6", "7", "8", "9"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 66,
    category: "Science",
    question: "Which planet has the most moons?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctAnswer: 1,
    difficulty: "hard",
  },
  {
    id: 67,
    category: "Science",
    question: "What is the name of the Earth's natural satellite?",
    options: ["Sun", "Moon", "Venus", "Mars"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 68,
    category: "Science",
    question: "What is the process by which plants convert light energy into chemical energy?",
    options: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"],
    correctAnswer: 1,
    difficulty: "medium",
  },

  // Geography Questions (15)
  {
    id: 69,
    category: "Geography",
    question: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 70,
    category: "Geography",
    question: "Which is the longest river in the world?",
    options: ["Amazon River", "Nile River", "Mississippi River", "Yangtze River"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 71,
    category: "Geography",
    question: "What is the smallest country in the world?",
    options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 72,
    category: "Geography",
    question: "Which mountain range contains Mount Everest?",
    options: ["Andes", "Rocky Mountains", "Alps", "Himalayas"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 73,
    category: "Geography",
    question: "What is the largest desert in the world?",
    options: ["Sahara Desert", "Gobi Desert", "Antarctica", "Arabian Desert"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 74,
    category: "Geography",
    question: "Which country has the most time zones?",
    options: ["Russia", "United States", "China", "Canada"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 75,
    category: "Geography",
    question: "What is the capital of Canada?",
    options: ["Toronto", "Vancouver", "Montreal", "Ottawa"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 76,
    category: "Geography",
    question: "Which ocean is the largest?",
    options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correctAnswer: 3,
    difficulty: "easy",
  },
  {
    id: 77,
    category: "Geography",
    question: "What is the highest waterfall in the world?",
    options: ["Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 78,
    category: "Geography",
    question: "Which African country was never colonized?",
    options: ["Kenya", "Ethiopia", "Ghana", "Nigeria"],
    correctAnswer: 1,
    difficulty: "hard",
  },
  {
    id: 79,
    category: "Geography",
    question: "What is the deepest point on Earth?",
    options: ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Peru-Chile Trench"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 80,
    category: "Geography",
    question: "Which country is both in Europe and Asia?",
    options: ["Russia", "Turkey", "Kazakhstan", "All of the above"],
    correctAnswer: 3,
    difficulty: "medium",
  },
  {
    id: 81,
    category: "Geography",
    question: "What is the largest island in the world?",
    options: ["Madagascar", "Greenland", "New Guinea", "Borneo"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 82,
    category: "Geography",
    question: "Which city is known as the 'City of Love'?",
    options: ["Rome", "Venice", "Paris", "Vienna"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 83,
    category: "Geography",
    question: "What is the driest place on Earth?",
    options: ["Death Valley", "Sahara Desert", "Atacama Desert", "Antarctic Desert"],
    correctAnswer: 2,
    difficulty: "hard",
  },
  {
    id: 84,
    category: "Geography",
    question: "What is the name of the largest lake in Africa?",
    options: ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 85,
    category: "Geography",
    question: "Which continent is also a country?",
    options: ["Asia", "Africa", "Australia", "Europe"],
    correctAnswer: 2,
    difficulty: "easy",
  },

  // History Questions (15)
  {
    id: 86,
    category: "History",
    question: "In which year did World War II end?",
    options: ["1944", "1945", "1946", "1947"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 87,
    category: "History",
    question: "Who was the first person to walk on the moon?",
    options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Alan Shepard"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 88,
    category: "History",
    question: "Who painted the ceiling of the Sistine Chapel?",
    options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 89,
    category: "History",
    question: "In which year did the Berlin Wall fall?",
    options: ["1987", "1988", "1989", "1990"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 90,
    category: "History",
    question: "Which ancient wonder of the world was located in Alexandria?",
    options: ["Hanging Gardens", "Colossus of Rhodes", "Lighthouse of Alexandria", "Temple of Artemis"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 91,
    category: "History",
    question: "Who was the first President of the United States?",
    options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 92,
    category: "History",
    question: "In which year did the Titanic sink?",
    options: ["1910", "1911", "1912", "1913"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 93,
    category: "History",
    question: "Which empire was ruled by Julius Caesar?",
    options: ["Greek Empire", "Roman Empire", "Byzantine Empire", "Ottoman Empire"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 94,
    category: "History",
    question: "Who invented the printing press?",
    options: ["Leonardo da Vinci", "Johannes Gutenberg", "Benjamin Franklin", "Thomas Edison"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 95,
    category: "History",
    question: "Which war was fought between the North and South in America?",
    options: ["Revolutionary War", "War of 1812", "Civil War", "Spanish-American War"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 96,
    category: "History",
    question: "Who was known as the 'Iron Lady'?",
    options: ["Queen Elizabeth II", "Margaret Thatcher", "Golda Meir", "Indira Gandhi"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 97,
    category: "History",
    question: "In which year did the French Revolution begin?",
    options: ["1789", "1790", "1791", "1792"],
    correctAnswer: 0,
    difficulty: "medium",
  },
  {
    id: 98,
    category: "History",
    question: "Which Egyptian queen was known for her relationships with Julius Caesar and Mark Antony?",
    options: ["Nefertiti", "Hatshepsut", "Cleopatra", "Ankhesenamun"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 99,
    category: "History",
    question: "What was the name of the ship on which Charles Darwin made his famous voyage?",
    options: ["HMS Victory", "HMS Beagle", "HMS Endeavour", "HMS Bounty"],
    correctAnswer: 1,
    difficulty: "hard",
  },
  {
    id: 100,
    category: "History",
    question: "Which city was the capital of the Byzantine Empire?",
    options: ["Rome", "Athens", "Constantinople", "Alexandria"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 101,
    category: "History",
    question: "Who was the first Roman Emperor?",
    options: ["Julius Caesar", "Augustus", "Nero", "Caligula"],
    correctAnswer: 1,
    difficulty: "medium",
  },
  {
    id: 102,
    category: "History",
    question: "What event is considered the start of the Great Depression?",
    options: ["World War I", "The Stock Market Crash of 1929", "The Dust Bowl", "The Treaty of Versailles"],
    correctAnswer: 1,
    difficulty: "medium",
  },

  // Sports Questions (15)
  {
    id: 103,
    category: "Sports",
    question: "How many players are on a basketball team on the court at one time?",
    options: ["4", "5", "6", "7"],
    correctAnswer: 1,
    difficulty: "easy",
  },
  {
    id: 104,
    category: "Sports",
    question: "In which sport would you perform a slam dunk?",
    options: ["Volleyball", "Tennis", "Basketball", "Baseball"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 105,
    category: "Sports",
    question: "How often are the Summer Olympic Games held?",
    options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"],
    correctAnswer: 2,
    difficulty: "easy",
  },
  {
    id: 106,
    category: "Sports",
    question: "What is the maximum score possible in ten-pin bowling?",
    options: ["200", "250", "300", "350"],
    correctAnswer: 2,
    difficulty: "medium",
  },
  {
    id: 107,
    category: "Sports",
    question: "In soccer, what body part can't touch the ball (except for goalkeepers)?",
    options: ["Head", "Hands", "Feet", "Legs"],
    correctAnswer: 1,
    difficulty: "easy",
  },
]
